"""
@file sipri_info.py

The data structures in this file are constants used for database operations on SIPRI's Arms Transfer Database.

@author Victor Mercola
@author Benjamin Lunden
@author Jack Ayvazian
"""
from typing import Dict, Tuple, List


ENTITY_DICT: Dict[str, Tuple[str, str]] = {
    "Afghanistan": ("AFG", "AFG"),
    # "African Union": ("AU", ""),
    "Albania": ("ALB", "ALB"),
    "Algeria": ("ALG", "DZA"),
    "Angola": ("ANG", "AGO"),
    "Argentina": ("ARG", "ARG"),
    "Armenia": ("ARM", "ARM"),
    "Aruba": ("ARU", "ABW"),  # Part of the Netherlands
    "Australia": ("AUS", "AUS"),
    "Austria": ("AST", "AUT"),
    "Azerbaijan": ("AZB", "AZE"),
    "Bahamas": ("BAS", "BHS"),
    "Bahrain": ("BAH", "BHR"),
    "Bangladesh": ("BAN", "BGD"),
    "Barbados": ("BAR", "BRB"),
    "Belarus": ("BLR", "BLR"),
    "Belgium": ("BEL", "BEL"),
    "Belize": ("BLZ", "BLZ"),
    "Benin": ("BEN", "BEN"),
    "Bhutan": ("BHU", "BTN"),
    "Bolivia": ("BOL", "BOL"),
    "Bosnia-Herzegovina": ("BOS", "BIH"),
    "Botswana": ("BOT", "BWA"),
    "Brazil": ("BRA", "BRA"),
    "Brunei": ("BRU", "BRN"),
    "Bulgaria": ("BUL", "BGR"),
    "Burkina Faso": ("BF", "BFA"),
    "Burundi": ("BDI", "BDI"),
    "Cabo Verde": ("CAP", "CPV"),
    "Cambodia": ("CMB", "KHM"),
    "Cameroon": ("CAM", "CMR"),
    "Canada": ("CAN", "CAN"),
    "Central African Republic": ("CAR", "CAF"),
    "Chad": ("CHA", "TCD"),
    "Chile": ("CHE", "CHL"),
    "China": ("CHI", "CHN"),
    "Colombia": ("COL", "COL"),
    "Comoros": ("COM", "COM"),
    "Congo": ("CON", "COG"),
    "Costa Rica": ("COS", "CRI"),
    "Cote d'Ivoire": ("IVO", "CIV"),
    "Croatia": ("CRO", "HRV"),
    "Cuba": ("CUB", "CUB"),
    "Cyprus": ("CYP", "CYP"),
    "Czechia": ("CZR", "CZE"),
    "DR Congo": ("DRC", "COD"),
    # "Darfur rebels (Sudan)*": ("XSD", ""),
    "Denmark": ("DEN", "DNK"),
    "Djibouti": ("DJI", "DJI"),
    "Dominican Republic": ("DOM", "DOM"),
    "Ecuador": ("ECU", "ECU"),
    "Egypt": ("EGY", "EGY"),
    "El Salvador": ("SAL", "SLV"),
    "Equatorial Guinea": ("EQU", "GNQ"),
    "Eritrea": ("ERI", "ERI"),
    "Estonia": ("EST", "EST"),
    "Ethiopia": ("ETH", "ETH"),
    "Fiji": ("FJI", "FJI"),
    "Finland": ("FIN", "FIN"),
    "France": ("FRA", "FRA"),
    "Gabon": ("GAB", "GAB"),
    "Gambia": ("GAM", "GMB"),
    "Georgia": ("GEO", "GEO"),
    "Germany": ("FRG", "DEU"),
    "Ghana": ("GHA", "GHA"),
    "Greece": ("GRE", "GRC"),
    "Guatemala": ("GUA", "GTM"),
    "Guinea": ("GUI", "GIN"),
    "Guinea-Bissau": ("GBI", "GNB"),
    "Guyana": ("GUY", "GUY"),
    "Haiti": ("HAI", "HTI"),
    # "Hamas (Palestine)*": ("XPA", ""),
    # "Hezbollah (Lebanon)*": ("XLH", ""),
    "Honduras": ("HON", "HND"),
    # "Houthi rebels (Yemen)*": ("XYH", ""),
    "Hungary": ("HUN", "HUN"),
    "Iceland": ("ICE", "ISL"),
    "India": ("IND", "IND"),
    "Indonesia": ("INS", "IDN"),
    "Iran": ("IRA", "IRN"),
    "Iraq": ("IRQ", "IRQ"),
    "Ireland": ("IRE", "IRL"),
    "Israel": ("ISR", "ISR"),
    "Italy": ("ITA", "ITA"),
    "Jamaica": ("JAM", "JAM"),
    "Japan": ("JAP", "JPN"),
    "Jordan": ("JOR", "JOR"),
    "Kazakhstan": ("KAZ", "KAZ"),
    "Kenya": ("KEN", "KEN"),
    "Kiribati": ("KIR", "KIR"),
    "Kosovo": ("KSV", "KSV"),  # Kosovo is disputed, UNK did not work
    "Kuwait": ("KUW", "KWT"),
    "Kyrgyzstan": ("KYR", "KGZ"),
    # "LRA (Uganda)": ("XUL", ""),
    # "LTTE (Sri Lanka)": ("XSL", ""),
    "Laos": ("LAO", "LAO"),
    "Latvia": ("LAT", "LVA"),
    "Lebanon": ("LEB", "LBN"),
    "Lesotho": ("LES", "LSO"),
    "Liberia": ("LIB", "LBR"),
    "Libya": ("LYA", "LBY"),
    # "Libya GNC": ("LYW", ""),
    # "Libya HoR": ("LYE", ""),
    "Lithuania": ("LIT", "LTU"),
    "Luxembourg": ("LUX", "LUX"),
    "Madagascar": ("MAD", "MDG"),
    "Malawi": ("MWI", "MWI"),
    "Malaysia": ("MAL", "MYS"),
    "Maldives": ("MLV", "MDV"),
    "Mali": ("MLI", "MLI"),
    "Malta": ("MTA", "MLT"),
    "Marshall Islands": ("MAR", "MHL"),
    "Mauritania": ("MRA", "MRT"),
    "Mauritius": ("MAU", "MUS"),
    "Mexico": ("MEX", "MEX"),
    "Micronesia": ("MIC", "FSM"),
    "Moldova": ("MOL", "MDA"),
    "Mongolia": ("MON", "MNG"),
    "Montenegro": ("MTG", "MNE"),
    "Morocco": ("MOR", "MAR"),
    "Mozambique": ("MOZ", "MOZ"),
    "Myanmar": ("MYA", "MMR"),
    # "NATO": ("NAT", ""),
    # "NLA (Macedonia)": ("XMN", ""),
    # "NTC (Libya)": ("XLB", ""),
    "Namibia": ("NAM", "NAM"),
    "Nepal": ("NEP", "NPL"),
    "Netherlands": ("NET", "NLD"),
    "New Zealand": ("NZ", "NZL"),
    "Nicaragua": ("NIC", "NIC"),
    "Niger": ("NIR", "NER"),
    "Nigeria": ("NIG", "NGA"),
    "North Korea": ("KON", "PRK"),
    "North Macedonia": ("MAC", "MKD"),
    # "Northern Alliance (Afghanistan)": ("XAN", ""),
    "Norway": ("NOR", "NOR"),
    # "OSCE": ("OSC", ""),
    "Oman": ("OMA", "OMN"),
    # "PIJ (Israel/Palestine)": ("XID", ""),
    # "PKK (Turkey)": ("XTP", ""),
    # "PRC (Israel/Palestine)": ("XPC", ""),
    "Pakistan": ("PAK", "PAK"),
    "Palau": ("PAL", "PLW"),
    "Palestine": ("PA", "PSE"),
    "Panama": ("PAN", "PAN"),
    "Papua New Guinea": ("PAP", "PNG"),
    "Paraguay": ("PAR", "PRY"),
    "Peru": ("PER", "PER"),
    "Philippines": ("PHI", "PHL"),
    "Poland": ("POL", "POL"),
    "Portugal": ("POR", "PRT"),
    "Qatar": ("QAT", "QAT"),
    # "RUF (Sierra Leone)": ("XSR", ""),
    # "Regional Security System": ("RSS", ""),
    "Romania": ("ROM", "ROU"),
    "Russia": ("RUS", "RUS"),
    "Rwanda": ("RWA", "RWA"),
    "Saint Kitts and Nevis": ("SKN", "KNA"),
    "Saint Vincent and the Grenadines": ("SVG", "VCT"),
    "Samoa": ("SAM", "WSM"),
    "Saudi Arabia": ("SAU", "SAU"),
    "Senegal": ("SEN", "SEN"),
    "Serbia": ("SER", "SRB"),
    "Seychelles": ("SEY", "SYC"),
    "Sierra Leone": ("SIE", "SLE"),
    "Singapore": ("SIN", "SGP"),
    "Slovakia": ("SLK", "SVK"),
    "Slovenia": ("SLO", "SVN"),
    "Solomon Islands": ("SOL", "SLB"),
    "Somalia": ("SOM", "SOM"),
    "South Africa": ("SA", "ZAF"),
    "South Korea": ("KOS", "KOR"),
    "South Sudan": ("SSD", "SSD"),
    "Spain": ("SPA", "ESP"),
    "Sri Lanka": ("SRI", "LKA"),
    "Sudan": ("SUD", "SDN"),
    "Suriname": ("SUR", "SUR"),
    "Sweden": ("SWE", "SWE"),
    "Switzerland": ("SWI", "CHE"),
    "Syria": ("SYR", "SYR"),
    # "Syria rebels": ("XSX", ""),
    "Taiwan": ("TAI", "TWN"),
    "Tajikistan": ("TAJ", "TJK"),
    "Tanzania": ("TAN", "TZA"),
    "Thailand": ("THA", "THA"),
    "Timor-Leste": ("ET", "TLS"),
    "Togo": ("TOG", "TGO"),
    "Tonga": ("TON", "TON"),
    "Trinidad and Tobago": ("TRI", "TTO"),
    "Tunisia": ("TUN", "TUN"),
    "Turkey": ("TUR", "TUR"),
    "Turkmenistan": ("TRK", "TKM"),
    "Tuvalu": ("TUV", "TUV"),
    "UAE": ("UAE", "ARE"),
    # "UIC (Somalia)": ("XSI", ""),
    "Uganda": ("UGA", "UGA"),
    "Ukraine": ("UKR", "UKR"),
    # "Ukraine Rebels": ("XUR", ""),
    "United Kingdom": ("UK", "GBR"),
    # "United Nations": ("UNO", ""),
    "United States": ("USA", "USA"),
    # "United Wa State (Myanmar)": ("XMU", ""),
    # "Unknown rebel group": ("XXU", ""),
    # "Unknown recipient(s)": ("XXR", ""),
    "Uruguay": ("URU", "URY"),
    "Uzbekistan": ("UZB", "UZB"),
    "Vanuatu": ("VAN", "VUT"),
    "Venezuela": ("VEN", "VEN"),
    "Viet Nam": ("VN", "VNM"),
    "Western Sahara": ("SAH", "ESH"),
    "Yemen": ("YEM", "YEM"),
    "Zambia": ("ZAM", "ZMB"),
    "Zimbabwe": ("ZIM", "ZWE"),
    "eSwatini": ("SWA", "SWZ"),
}
"""
Dictionary that maps a SIPRI entity's full name to a tuple containing the entity's corresponding SIPRI code and ISO 
alpha-3 code.
"""

# SIPRI_CODES: List[str] = list(map(lambda x: x[0], ENTITY_DICT.values()))
# """
# List of SIPRI codes. Deprecated because it already can be derived from ENTITY_DICT.
# """

CSV_HEADER: str = "tidn,buyercod,sellercod,odat,odai,onum,onai,ldat,term,desig2,wcat,desc,coprod,nrdel,nrdelai," \
                  "delyears,buyer,seller,status,tivunit,tivorder,tivdel "
"""
Default SIPRI CSV header.
"""

WCATS_DICT = {
    "AC": "Aircraft",
    "AR": "Artillery",
    "AV": "Armored vehicles",
    "EN": "Engines",
    "GR": "Sensors",
    "MI": "Missiles",
    "SH": "Ships",
    "OT": "Other",
    "NW": "Naval weapons",
    "SA": "Satellites",
    "AD": "Air defense"
}
"""
Dictionary that maps SIPRI weapon categories to their descriptions.
"""
